-- ClearNet DB Schema
-- Version 1.0

-- 1. PROFILES TABLE
-- This table stores public user profile information. It is linked to the auth.users table.
CREATE TABLE public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    updated_at TIMESTAMPTZ,
    full_name TEXT,
    avatar_url TEXT,
    bio TEXT,
    CONSTRAINT full_name_length CHECK (char_length(full_name) >= 3)
);

-- Comments for Profiles Table
COMMENT ON TABLE public.profiles IS 'User profile information, linked to authentication user.';
COMMENT ON COLUMN public.profiles.id IS 'Links to auth.users.id.';

-- 2. INTENTS TABLE
-- Stores the predefined intents users can select (e.g., "seeking collaborators").
CREATE TABLE public.intents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    description TEXT
);

-- Comments for Intents Table
COMMENT ON TABLE public.intents IS 'Predefined professional intents users can select.';

-- 3. USER_INTENTS JUNCTION TABLE
-- Links users to their selected intents in a many-to-many relationship.
CREATE TABLE public.user_intents (
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    intent_id BIGINT NOT NULL REFERENCES public.intents(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (user_id, intent_id)
);

-- Comments for User_Intents Table
COMMENT ON TABLE public.user_intents IS 'Junction table linking users to their professional intents.';

-- 4. PERMISSIONS TABLE
-- Stores user-specific permissions and settings, especially for messaging and privacy.
CREATE TABLE public.permissions (
    user_id UUID PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
    updated_at TIMESTAMPTZ,
    allow_all_messages BOOLEAN DEFAULT FALSE NOT NULL,
    allow_group_invites BOOLEAN DEFAULT TRUE NOT NULL
);

-- Comments for Permissions Table
COMMENT ON TABLE public.permissions IS 'User-specific permissions for messaging and privacy.';


-- SETUP ROW LEVEL SECURITY (RLS)
-- Enable RLS for all tables
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.intents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_intents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.permissions ENABLE ROW LEVEL SECURITY;

-- RLS POLICIES
-- Profiles: Users can see all profiles, but only edit their own.
CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles
    FOR SELECT USING (true);

CREATE POLICY "Users can insert their own profile." ON public.profiles
    FOR INSERT WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update their own profile." ON public.profiles
    FOR UPDATE USING (auth.uid() = id);

-- Intents: All users can view the available intents.
CREATE POLICY "Intents are viewable by everyone." ON public.intents
    FOR SELECT USING (true);

-- User_Intents: Users can view all user-intent links, but only manage their own.
CREATE POLICY "User-intent links are viewable by everyone." ON public.user_intents
    FOR SELECT USING (true);

CREATE POLICY "Users can insert their own intents." ON public.user_intents
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own intents." ON public.user_intents
    FOR DELETE USING (auth.uid() = user_id);

-- Permissions: Users can only view and edit their own permissions.
CREATE POLICY "Users can view their own permissions." ON public.permissions
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own permissions." ON public.permissions
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own permissions." ON public.permissions
    FOR UPDATE USING (auth.uid() = user_id);

-- SEED DATA for Intents
-- Insert some initial intents to get started.
INSERT INTO public.intents (name, description) VALUES
('Open to work', 'Actively looking for new job opportunities.'),
('Seeking collaborators', 'Looking for partners for projects.'),
('Offering mentorship', 'Willing to mentor other professionals.'),
('Seeking mentorship', 'Looking for a mentor.'),
('Hiring', 'Looking to hire talent for my team or company.');

